name: Build and test run

on: [push,pull_request]
jobs:
  on-push:
    if: gitgub.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
      - uses: actions/checkout@v4
        run: echo "push detected"

  on-pull-request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@4
        with:
         distribution: 'temurin'
         java-version: '17'
      - name: Build with maven
        run: mvn clean install