name: Build and test run

on: [push,pull_request]
jobs:
  on-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: checkout code
        run: echo "push detected"